// src/lib/ThemeToggle.svelte
<!-- src/lib/component/ThemeToggle.svelte -->
<script>
  import { onMount } from "svelte";

  export let size = "1.25em";
  export let pad = "0.25em";
  let checked;

  onMount(() => {
    let mediaColorScheme = window.matchMedia("(prefers-color-scheme: dark)");
    let prefersDarkScheme = mediaColorScheme.matches;
    let theme = localStorage.getItem("theme");

    checked = prefersDarkScheme;

    if (theme) {
      checked = theme === "dark";
    }

    setTheme();
  });

  function setTheme() {
    let bodyClasses = document.querySelector("body").classList;
    let theme;
    if (checked) {
      bodyClasses.remove("light-mode");
      theme = "dark";
    } else {
      bodyClasses.add("light-mode");
      theme = "light";
    }
    localStorage.setItem("theme", theme);
  }
</script>

<label class="toggle" style="--toggle-size: {size}; --toggle-pad: {pad};">
  <span class="sr-only">Light</span>
  <input type="checkbox" bind:checked on:change={setTheme} />
  <span class="wrapper">
    <span class="handle">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="icon icon-tabler icon-tabler-sun"
        width="44"
        height="44"
        viewBox="0 0 30 30"
        stroke="#000000"
        stroke-width="1.5"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <circle cx="12" cy="12" r="4" />
        <path
          d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"
        />
      </svg>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="icon icon-tabler icon-tabler-moon"
        width="44"
        height="44"
        viewBox="0 0 30 30"
        stroke-width="1.5"
        stroke="#000000"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
        <path
          d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"
        />
      </svg>
    </span>
  </span>
  <span class="sr-only">Dark</span>
</label>

<style lang="postcss">
  .toggle {
    position: relative;
    font-size: 2rem;
    font-weight: 700;
    letter-spacing: -0.05em;
  }

  .toggle input {
    visibility: hidden;
    position: absolute;
  }

  .wrapper,
  .handle {
    display: inline-block;
    border-radius: 2em;
  }

  .wrapper {
    box-sizing: content-box;
    width: calc(var(--toggle-size) * 2);
    height: var(--toggle-size);
    padding: var(--toggle-pad);
    vertical-align: calc(var(--toggle-pad) * -1);

    background: rgb(0 0 0 / 0.3);
  }

  .handle {
    position: relative;
    height: var(--toggle-size);
    width: var(--toggle-size);

    background: rgb(255 255 255);
    transition: transform 180ms ease;
    box-shadow: 0 0.25em 0.5em rgb(0 0 0 / 0.2);
  }

  .toggle input:checked ~ .wrapper {
    background: rgb(0 0 0 / 0.5);
  }

  .toggle input:checked ~ .wrapper .handle {
    background: rgb(255 255 255 / 0.8);
    transform: translatex(100%);
  }

  .icon {
    position: absolute;
    top: 0.0625em;
    left: 0.0625em;
    stroke: var(--text-color);
    transition: opacity 250ms;
  }

  .icon-tabler-moon {
    opacity: 0;
    left: 0.125em;
    stroke: var(--bg-color);
  }

  .toggle input:checked ~ span .icon-tabler-moon {
    opacity: 1;
  }

  .toggle input:checked ~ span .icon-tabler-sun {
    opacity: 0;
  }
</style>

// src/components/ThemeToggle.tsx
import { createEffect, createSignal, onMount } from "solid-js";
import ss from "./ThemeToggle.module.css";
import { cl } from "@/lib/utils";

export function ThemeToggle() {
  let [theme, setTheme] = createSignal<"light" | "dark">("light");
  let [hasTransition, setHasTransition] = createSignal(false);

  function toggle() {
    setTheme((c) => (c === "light" ? "dark" : "light"));
    localStorage.setItem("theme", theme());
  }

  function addTransition() {
    setHasTransition(true);
  }

  onMount(() => {
    const themePreference = window.matchMedia("(prefers-color-scheme: dark)")
      .matches
      ? "dark"
      : "light";
    setTheme(localStorage.theme || themePreference);
  });

  createEffect(() => {
    (document.firstElementChild as HTMLElement).dataset.theme = theme();
  });

  return (
    <button
      class={cl(ss.button, ss.toggle, theme() === "dark" && ss.dark)}
      style="--toggle-size: 1em; --toggle-pad: 0.15em;"
      onClick={toggle}
    >
      <span
        classList={{ [ss.handle!]: true, [ss.transition!]: hasTransition() }}
        onAnimationEnd={addTransition}
      >
        <span class="sr-only">Light</span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class={`${ss.icon} ${ss.iconSun}`}
          width="44"
          height="44"
          viewBox="0 0 24 24"
          stroke="#000000"
          stroke-width="1.5"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <circle cx="12" cy="12" r="4" />
          <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7" />
        </svg>
        <span class="sr-only">Dark</span>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class={`${ss.icon} ${ss.iconMoon}`}
          width="44"
          height="44"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="#000000"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z" />
        </svg>
      </span>
    </button>
  );
}
